import type { ViewSemanticProps, ViewStyleProps } from './view-types'

const VIEW_STYLE_PROP_KEYS = [
  'layout',
  'direction',
  'wrap',
  'gap',
  'align',
  'justify',
  'grow',
  'shrink',
  'basis',
  'alignSelf',
  'justifySelf',
  'order',
  'columns',
  'rows',
  'column',
  'columnSpan',
  'row',
  'rowSpan',
  'width',
  'height',
  'minWidth',
  'maxWidth',
  'minHeight',
  'maxHeight',
  'aspectRatio',
  'margin',
  'marginX',
  'marginY',
  'marginTop',
  'marginRight',
  'marginBottom',
  'marginLeft',
  'padding',
  'paddingX',
  'paddingY',
  'paddingTop',
  'paddingRight',
  'paddingBottom',
  'paddingLeft',
  'position',
  'inset',
  'insetX',
  'insetY',
  'top',
  'right',
  'bottom',
  'left',
  'overflow',
  'overflowX',
  'overflowY',
  'background',
  'color',
  'border',
  'borderTop',
  'borderRight',
  'borderBottom',
  'borderLeft',
  'borderColor',
  'borderTopColor',
  'borderRightColor',
  'borderBottomColor',
  'borderLeftColor',
  'borderStyle',
  'radius',
  'radiusTopLeft',
  'radiusTopRight',
  'radiusBottomRight',
  'radiusBottomLeft',
  'shadow',
  'opacity',
  'blur',
  'brightness',
  'contrast',
  'saturate',
  'grayscale',
  'sepia',
  'hueRotate',
  'backdropBlur',
  'backdropSaturate',
  'translateX',
  'translateY',
  'scale',
  'scaleX',
  'scaleY',
  'rotate',
  'skewX',
  'skewY',
  'transform',
  'transformOrigin',
  'mask',
  'clip',
  'blend',
  'outlineWidth',
  'outlineColor',
  'outlineStyle',
  'outlineOffset',
  'layer',
  'zIndex',
  'pointerEvents',
  'cursor',
  'selectable',
] as const satisfies readonly (keyof ViewStyleProps)[]

const VIEW_SEMANTIC_PROP_KEYS = [
  'role',
  'label',
  'description',
  'level',
  'disabled',
  'required',
  'invalid',
  'busy',
  'expanded',
  'selected',
  'checked',
  'pressed',
  'readOnly',
  'valueMin',
  'valueMax',
  'valueNow',
  'valueText',
  'labelledBy',
  'describedBy',
  'controls',
  'owns',
] as const satisfies readonly (keyof ViewSemanticProps)[]

const VIEW_DEFAULT_BREAKPOINT_PROP_KEYS = [
  'sm',
  'md',
  'lg',
  'xl',
  'containerSm',
  'containerMd',
  'containerLg',
  'containerXl',
] as const

const VIEW_NATIVE_NORMALIZED_PROP_KEYS = ['hidden', 'draggable', 'tabIndex'] as const

const VIEW_CONTROL_PROP_KEYS = [
  'children',
  'ref',
  'className',
  'style',
  'data',
  'clickable',
  'focusable',
  'autoFocus',
  'hover',
  'active',
  'focus',
  'focusVisible',
  'disabledStyle',
  'container',
  'scrollbar',
  'transition',
  'enter',
  'exit',
  'animation',
  'layoutAnimation',
] as const

export const VIEW_INTERNAL_PROP_KEYS = new Set<string>([
  ...VIEW_STYLE_PROP_KEYS,
  ...VIEW_SEMANTIC_PROP_KEYS,
  ...VIEW_DEFAULT_BREAKPOINT_PROP_KEYS,
  ...VIEW_NATIVE_NORMALIZED_PROP_KEYS,
  ...VIEW_CONTROL_PROP_KEYS,
])

type AssertNoMissingKeys<T extends never> = T

declare const _viewStylePropKeyCoverage: AssertNoMissingKeys<
  Exclude<keyof ViewStyleProps, (typeof VIEW_STYLE_PROP_KEYS)[number]>
>

declare const _viewSemanticPropKeyCoverage: AssertNoMissingKeys<
  Exclude<keyof ViewSemanticProps, (typeof VIEW_SEMANTIC_PROP_KEYS)[number]>
>
